### ISSUE TITLE
AIRPORT COMM not parsed

### ISSUE THREAD

**Issue by JanC** [jlmcgraw/parseCifp#2]
Hi again :)

I see that the AIRPORT COMM (PV) is defined in the [parsers.pl](https://github.com/jlmcgraw/parseCifp/blob/master/parsers.pl#L1309-L1346) and in the [sections.pl](https://github.com/jlmcgraw/parseCifp/blob/master/sections.pl#L42) but there is no `Airport - Communications` table created. 

I'm trying to debug this but maybe you have an idea 🙏 

cheers

**Comment by jlmcgraw** [comment]
Unfortunately, not all data is actually present in the CIFP to be parsed, though the FAA is adding more all the time.

Can you check that the data is actually in the CIFP?  If it is, and isn't parsing, I will fix.

In the meantime, take a look at the NASR parser if you're looking for frequency information for airports, ATC etc

**Comment by jlmcgraw** [comment]
The output at the end of a run shows you all of the primary and continuation records the parser found in that CIFP

For example:

Types of records found in ./CIFP_201713/FAACIFP18
$VAR1 = {
          'continuation' => {
                              'P' => {
                                       'F' => {
                                                'W' => 1
                                              },
                                       'P' => {
                                                'E' => 1
                                              }
                                     },
                              'U' => {
                                       'R' => {
                                                'C' => 1
                                              }
                                     }
                            },
          'primary' => {
                         'A' => {
                                  'S' => {
                                           'base' => 1
                                         }
                                },
                         'D' => {
                                  '' => {
                                          'base' => 1
                                        },
                                  'B' => {
                                           'base' => 1
                                         }
                                },
                         'E' => {
                                  'A' => {
                                           'base' => 1
                                         },
                                  'R' => {
                                           'base' => 1
                                         }
                                },
                         'H' => {
                                  'A' => {
                                           'base' => 1
                                         },
                                  'C' => {
                                           'base' => 1
                                         },
                                  'F' => {
                                           'base' => 1
                                         },
                                  'S' => {
                                           'base' => 1
                                         }
                                },
                         'P' => {
                                  'A' => {
                                           'base' => 1
                                         },
                                  'C' => {
                                           'base' => 1
                                         },
                                  'D' => {
                                           'base' => 1
                                         },
                                  'E' => {
                                           'base' => 1
                                         },
                                  'F' => {
                                           'base' => 1
                                         },
                                  'G' => {
                                           'base' => 1
                                         },
                                  'I' => {
                                           'base' => 1
                                         },
                                  'N' => {
                                           'base' => 1
                                         },
                                  'P' => {
                                           'base' => 1
                                         },
                                  'S' => {
                                           'base' => 1
                                         }
                                },
                         'U' => {
                                  'C' => {
                                           'base' => 1
                                         },
                                  'R' => {
                                           'base' => 1
                                         }
                                }
                       }
        };

**Comment by JanC** [comment]
Hi,
> Unfortunately, not all data is actually present in the CIFP to be parsed,

Ok I believe that’s the reason. It’s bummer, I thought FAA were giving all the documented data ..

I’ll have a look at the NASR data and parser, thanks.

**Comment by JanC** [comment]
> I'm basically looking for the geo shapes of airspaces

Nevermind, I see the airspaces are in the nasr database as spatialite gemotries. From there I can generate the geojson using `SELECT NAME, AsGeoJSON(GEOMETRY) ...`
